Repository kitops-ml/kitops, pull requests merged in 2024-05, with the labels that each got.

#303 Generate a dynamic sitemap.xml on build
  docs/.vitepress/config.mts
  docs/package.json
  docs/pnpm-lock.yaml
Labels: enhancement

#315 Update installation guide
  docs/src/docs/cli/installation.md
  docs/src/docs/quick-start.md
Labels: documentation

#316 dev mode updates
  README.md
  ROADMAP.md
  docs/src/docs/modelkit/compatibility.md
  docs/src/docs/quick-start.md
Labels: documentation

#318 new dev commands
  docs/src/docs/next-steps.md
  docs/src/docs/quick-start.md
Labels: documentation

#321 link fixes
  docs/src/docs/cli/installation.md
Labels: bug, documentation
