Repository kitops-ml/kitops, pull requests merged in 2024-03, with the labels that each got.

#101 New getting started doc
  README.md
  docs/.vitepress/config.mts
  docs/src/docs/kitfile/kf-overview.md
  docs/src/docs/kitfile/structure.md
  docs/src/docs/overview.md
  docs/src/docs/quick-start.md
  docs/src/docs/use-cases.md
  docs/src/docs/why-kitops.md
Labels: documentation, enhancement

#89 Update how default config directory is handled
  cmd/root.go
  docs/src/docs/cli/cli-reference.md
  pkg/cmd/list/cmd.go
  pkg/cmd/pull/cmd.go
  pkg/cmd/push/cmd.go
  pkg/cmd/remove/cmd.go
  pkg/cmd/unpack/cmd.go
  pkg/lib/constants/consts.go
Labels: enhancement, CLI

#61 Add Dockerfile for installing kit as a KServe ClusterStorageContainer
  build/dockerfiles/KServe/README.md
  build/dockerfiles/KServe/entrypoint.sh
  build/dockerfiles/KServe/kserve.Dockerfile
Labels: enhancement, ModelKit

#150 Update quick-start.md
  docs/src/docs/quick-start.md
Labels: documentation, enhancement

#155 remove commented blocks
  docs/src/docs/quick-start.md
Labels: documentation, enhancement

#156 added next-steps.md
  docs/src/docs/next-steps.md
  docs/src/docs/quick-start.md
Labels: documentation, enhancement

#174 add next steps to nav
  docs/.vitepress/config.mts
Labels: bug, documentation
